spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/clientpulse
spring.datasource.username=root
spring.datasource.password=NewStrongPassword@123
spring.jpa.hibernate.ddl-auto=update